<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>osu! with an additional "Perfect Aim" timing-practice mod.</Description>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game\osu.Game.csproj" />
    <ProjectReference Include="..\osu.Game.Rulesets.Osu\osu.Game.Rulesets.Osu.csproj" />
  </ItemGroup>
</Project>
